// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export async function getRoutes() {
  const routes = {"1":{"path":"/login","parentId":"@@/global-layout","id":"1"},"2":{"path":"","parentId":"3","id":"2","originPath":"/"},"3":{"path":"/","isWrapper":true,"parentId":"@@/global-layout","id":"3"},"4":{"path":"/home","parentId":"2","id":"4"},"5":{"path":"/user","parentId":"2","id":"5"},"6":{"path":"/system","parentId":"2","id":"6"},"7":{"name":"user-mt","path":"/system/user","parentId":"6","id":"7"},"8":{"name":"user-mt-detail","path":"/system/user:userId","parentId":"6","id":"8"},"9":{"name":"role-mt","path":"/system/role","parentId":"6","id":"9"},"10":{"path":"/","redirect":"/home","parentId":"2","id":"10"},"11":{"path":"/:catchAll(.*)","parentId":"2","id":"11"},"@@/global-layout":{"id":"@@/global-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': () => import(/* webpackChunkName: "p__login__index" */'@/pages/login/index.vue'),
'2': () => import(/* webpackChunkName: "layouts__index" */'@/layouts/index.vue'),
'3': () => import(/* webpackChunkName: "wrappers__index" */'@/wrappers/index.vue'),
'4': () => import(/* webpackChunkName: "p__home__index" */'@/pages/home/index.vue'),
'5': () => import(/* webpackChunkName: "p__user__index" */'@/pages/user/index.vue'),
'6': () => import('./EmptyRoute'),
'7': () => import(/* webpackChunkName: "p__system__user" */'@/pages/system/user.vue'),
'8': () => import(/* webpackChunkName: "p__system__user-detail" */'@/pages/system/user-detail.vue'),
'9': () => import(/* webpackChunkName: "p__system__roles" */'@/pages/system/roles.vue'),
'10': () => import('./EmptyRoute'),
'11': () => import(/* webpackChunkName: "p__404" */'@/pages/404.vue'),
'@@/global-layout': () => import(/* webpackChunkName: "layouts__index" */'/Users/mayapeng/Documents/Github/umijs-vue/src/layouts/index.vue'),
},
  };
}
