// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// defineApp
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// plugins
export { useAppData } from '/Users/mayapeng/Documents/Github/umijs-vue/src/.umi/plugin-vue';
// plugins types.d.ts
// @umijs/renderer-*
export { createMemoryHistory, createRouter, createWebHashHistory, createWebHistory, onBeforeRouteLeave, onBeforeRouteUpdate, RouterLink, RouterView, useLink, useRoute, useRouter, AppContextKey, renderClient } from '/Users/mayapeng/Documents/Github/umijs-vue/node_modules/.pnpm/@umijs+renderer-vue@4.4.6_vue-router@4.1.6_vue@3.2.45__vue@3.2.45/node_modules/@umijs/renderer-vue';
export type { History, ClientLoader } from '/Users/mayapeng/Documents/Github/umijs-vue/node_modules/.pnpm/@umijs+renderer-vue@4.4.6_vue-router@4.1.6_vue@3.2.45__vue@3.2.45/node_modules/@umijs/renderer-vue'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from '/Users/mayapeng/Documents/Github/umijs-vue/node_modules/.pnpm/umi@4.4.6_@babel+core@7.26.10_@types+node@22.13.10_eslint@8.57.1_jest@29.7.0_@types+nod_b6e3d13562d2fde83bf201c884b95b1a/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
